version: 2
registries:
  jfrog:
    type: maven-repository
    url: https://zextras.jfrog.io/artifactory
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "chore/dependabot"
    registries:
      - jfrog
    schedule:
      interval: "daily"
